### ISSUE TITLE
ERROR: There was an uncaught exception...Cannot find module 'request'

### ISSUE THREAD

**Issue by BerkSmash1984** [jmwyds/MMM-WordOfTheDay#2]
Hello, upon installing this module and running npm start, the following is seen in Electron and my MagicMirror fail to load. If I disabled the module, it works fine. Any thoughts? Are you aware of any issues with your module? I am running on a RPI4
```
[11.05.2022 09:11.08.814] [ERROR] App threw an error during load
[11.05.2022 09:11.08.815] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/jberk1984/MagicMirror/modules/MMM-WordOfTheDay/node_helper.js
- /home/jberk1984/MagicMirror/js/app.js
- /home/jberk1984/MagicMirror/js/electron.js
- /home/jberk1984/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Function.Module._resolveFilename (/home/jberk1984/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/jberk1984/MagicMirror/modules/MMM-WordOfTheDay/node_helper.js:9:15)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadModule (/home/jberk1984/MagicMirror/js/app.js:127:19)
    at loadNextModule (/home/jberk1984/MagicMirror/js/app.js:165:5)
    at /home/jberk1984/MagicMirror/js/app.js:167:6
    at Class.loaded (/home/jberk1984/MagicMirror/js/node_helper.js:18:3)
    at loadModule (/home/jberk1984/MagicMirror/js/app.js:144:6)
    at loadNextModule (/home/jberk1984/MagicMirror/js/app.js:165:5)
    at /home/jberk1984/MagicMirror/js/app.js:167:6
[11.05.2022 09:11.08.816] [ERROR] Whoops! There was an uncaught exception...
[11.05.2022 09:11.08.821] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/jberk1984/MagicMirror/modules/MMM-WordOfTheDay/node_helper.js
- /home/jberk1984/MagicMirror/js/app.js
- /home/jberk1984/MagicMirror/js/electron.js
- /home/jberk1984/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Function.Module._resolveFilename (/home/jberk1984/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/jberk1984/MagicMirror/modules/MMM-WordOfTheDay/node_helper.js:9:15)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadModule (/home/jberk1984/MagicMirror/js/app.js:127:19)
    at loadNextModule (/home/jberk1984/MagicMirror/js/app.js:165:5)
    at /home/jberk1984/MagicMirror/js/app.js:167:6
    at Class.loaded (/home/jberk1984/MagicMirror/js/node_helper.js:18:3)
    at loadModule (/home/jberk1984/MagicMirror/js/app.js:144:6)
    at loadNextModule (/home/jberk1984/MagicMirror/js/app.js:165:5)
    at /home/jberk1984/MagicMirror/js/app.js:167:6 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/jberk1984/MagicMirror/modules/MMM-WordOfTheDay/node_helper.js',
    '/home/jberk1984/MagicMirror/js/app.js',
    '/home/jberk1984/MagicMirror/js/electron.js',
    '/home/jberk1984/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
```

**Comment by DaveChild** [comment]
I had the same thing, you can solve it with something like:

    cd ~/MagicMirror
    npm install request --save

**Comment by droldanbascon** [comment]
> 
Hi, that doesnt work forme.
I got this:
<img width="327" alt="image" src="https://user-images.githubusercontent.com/118904381/206922411-05b17c54-ba69-45be-9a3f-99547eaffdf8.png">

**Comment by honeystreamguy** [comment]
> I had the same thing, you can solve it with something like:
> 
> ```
> cd ~/MagicMirror
> npm install request --save
> ```

This worked for me. Thank you!
